on:
  push:
    branches:
      - master
    tags:
      - 'v*'

name: Generalized Deployments
jobs:
  push:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
      with:
        role-to-assume: ${{ secrets.GDBP_AWS_IAM_ROLE_ARN }}
        aws-region: us-west-2

    - name: Deploy to Production
      if: startsWith(github.ref, 'refs/tags/')
      uses: brave-intl/general-docker-build-pipeline-action@ab4a4670c7623cac5ce795f53ee36d75b7ad17fc # v1.0.32
      env:
        GITHUB_REF_OVERRIDE: refs/heads/production

    - name: Deploy Branch
      if: github.ref == 'refs/heads/master'
      uses: brave-intl/general-docker-build-pipeline-action@ab4a4670c7623cac5ce795f53ee36d75b7ad17fc # v1.0.32
